AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  crypto-dashboard

  SAM Template for the Crypto Dashboard project. This contains all the config for the serverless aspect of the project.

Resources:
  GetCoinDataFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: crypto/
      Handler: app.lambdaHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64

